config/routes.rb
Rails.application.routes.draw do
  resources :points, only: [:index] do
    post :deposit, on: :collection
  end

  devise_for :users

  resources :home, only: [:index] do
    get :leaderboard, on: :collection
    get :help, on: :collection
  end

  root to: "home#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :user

  validates :amount, numericality: { greater_than_or_equal_to: 0 }

  def add_points!(added_amount)
    if added_amount.is_a? Numeric
      self.amount += added_amount
      save!
    else
      # TODO throw error
    end
  end

  def remove_points!(removed_amount)
    if removed_amount.is_a? Numeric
      self.amount -= removed_amount
      save!
    else
      # TODO throw error
    end
  end
end

app/models/point_transaction.rb
class PointTransaction < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :reciever, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :points, class_name: 'Point'
  validates_presence_of :points

  before_validation(on: :create) do
    if self.points.nil?
      self.points = Point.create(amount: 1000.00)
    end
  end

  has_many :sent_transactions, as: :sender, foreign_key: :sender_id
  has_many :recieved_transactions, as: :reciever, foreign_key: :reciever_id

  before_validation

protected
  # TODO remove this before live
  def confirmation_required?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def help
  end

  def leaderboard
    @points = Point.all.includes(:user).order(amount: :desc)
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  def index
    @transactions = PointTransaction.where('sender_id=? OR reciever_id=?', current_user.id, current_user.id).order(created_at: :desc)
  end

  def deposit
    unless params[:amount].present? and  reciever = User.find(params[:reciever])
      flash[:warning] = "Failed to send points"
      redirect_to points_path
      return
    end

    if current_user == reciever
      flash[:danger] = "Try to give yourself points.... for shame...."
      redirect_to points_path
      return
    end

    amount = BigDecimal.new(params[:amount])

    if amount >= current_user.points.amount
      flash[:warning] = "You don't have enough points to send #{amount.to_s}"
      redirect_to points_path
      return
    elsif amount <= 0
      flash[:warning] = "There's no such thing as a negative point, and sending 0 points is frowned upon >:("
      redirect_to points_path
      return
    end

    ActiveRecord::Base.transaction do
      point_transaction = PointTransaction.new(sender: current_user, reciever: reciever, amount: amount, is_committed: true)
      current_user.points.remove_points!(amount)
      reciever.points.add_points!(amount)
      point_transaction.save!
    end

    flash[:success] = "You have deposited #{amount.to_s} points with #{reciever.email}.  Now you just have to get them back some day!"
    redirect_to points_path
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bank_helper.rb
module BankHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/help.html.erb
<h1>Information on how this works</h1>

app/views/home/index.html.erb
<div class="header clearfix">
  <nav>
    <ul class="nav nav-pills float-right">
      <li class="nav-item">
        <a class="nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to "Leaderboard", leaderboard_home_index_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Help", help_home_index_path, class: 'nav-link' %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Signout", destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </nav>
  <h3 class="text-muted">Everyone Gets A Thousand</h3>
</div>

<div class="jumbotron">
  <h1 class="display-3">This is a fun game!</h1>
  <p class="lead">You get a thousand points when you start.  You want to have the most points.  You may trade points with each other.</p>
  <% unless user_signed_in? %>
    <p><%= link_to "Sign up today", new_user_registration_path, class: "btn btn-lg btn-primary" %></p>
    <p><%= link_to "Login", new_user_session_path, class: "btn btn-lg btn-secondary" %></p>
  <% else %>
    <p><%= link_to "View Points Log", points_path, class: "btn btn-lg btn-primary" %></p>
    <p><%= link_to "Help", help_home_index_path, class: "btn btn-lg btn-secondary" %></p>
  <% end %>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4></h4>
    <p></p>

    <h4></h4>
    <p></p>

    <h4></h4>
    <p></p>
  </div>

  <div class="col-lg-6">
    <h4></h4>
    <p></p>

    <h4></h4>
    <p></p>

    <h4></h4>
    <p></p>
  </div>
</div>

<footer class="footer">
  <p>&copy; EveryoneGetsAThousand 2017</p>
</footer>

app/views/home/leaderboard.html.erb
<div class="col-6">
<h1>Who's who of having points!</h1>

<ul class="list-group">
  <% @points.each do |point| %>
  <li class="list-group-item justify-content-between">
    <span class="badge badge-default badge-pill"><%= point.amount %></span>
    <%= point.user.email %>
  </li>
  <% end %>
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EveryoneGetsAThousand</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/points/index.html.erb
<h1>Points Log</h1>
<p>View your points, send someone points, view transaction history</p>

<h3>Current Points Total: <span class="badge badge-default badge-pill"><%= current_user.points.amount.to_s %></span></h3>
<hr />
<h2>Send Points:</h2>

<%= form_tag deposit_points_url, method: :post do |f| %>
  <div class="form-group">
    <%= select_tag :reciever, options_from_collection_for_select(User.where.not(id: current_user.id).all, "id", "email"), class: 'custom-select' %>
    <div class="form-group row">
      <label for="amount" class="col-2 col-form-label">Deposit Amount</label>
      <div class="col-10">
        <input class="form-control" type="number" id="amount" name="amount">
      </div>
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Deposit</button>
<% end %>

<h2>Transaction Log</h2>
All points changes on record
<table class="table table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Sender</th>
      <th>Reciever</th>
      <th>Amount</th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <th scope="row"><%= transaction.created_at %></th>
        <td><%= transaction.sender.email %></td>
        <td><%= transaction.reciever.email %></td>
        <% if transaction.reciever == current_user %>
          <td><span class="badge badge-default badge-pill"><%= transaction.amount %></span></td>
        <% else %>
          <td><span class="badge badge-danger badge-pill"><%= transaction.amount %></span></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/points/send_points.html.erb
<h1>Send Points</h1>